In [18]:
escolha = input("Digite qual operação você deseja realizar: 'Soma','Subtração','Multiplicação','Divisão' ")
num1 = int(input("Digite o primeiro número da operação: "))
num2 = int(input("Digite o segundo número da operação: "))

if escolha == "Soma":
                 print(num1 + num2)
elif escolha == "Subtração":
                 print(num1 - num2)
elif escolha == "Multiplicação":
                 print(num1 * num2)
elif escolha == "Divisão":
                 print(num1 / num2)
else:
    print("A operação desejada não existe.")
    

Digite qual operação você deseja realizar: 'Soma','Subtração','Multiplicação','Divisão'  Subtração
Digite o primeiro número da operação:  5
Digite o segundo número da operação:  6


-1


In [22]:
Celsius = float(input("Digite quantos celsius está hoje fazendo: ")) 
conversao = Celsius * 9/5 + 32
print(f"Está fazendo graus {conversao} Fahrenheit hoje. ")

Digite quantos celsius está hoje fazendo:  3


Está fazendo graus 37.4 Fahrenheit hoje. 


In [32]:
numero = int(input("Digite um número: "))
if numero % 2 == 0:
    Print("O número escolhido é par.")
else:
    print("O número escolhido é ímpar.")
             

Digite um número:  3


O número escolhido é ímpar.


In [38]:
nota1 = float(input("Digite a nota da sua primeira prova: "))
nota2 = float(input("Digite a nota da sua segunda prova: "))
nota3  = float(input("Digite a nota da sua terceira prova: "))

total = nota1 + nota2 + nota3
media = total / 3

if media >= 7:
    print("Aprovado")
elif media >= 5 and media < 7:
    print("Recuperação")
else:
    print("Reprovado")



Digite a nota da sua primeira prova:  9
Digite a nota da sua segunda prova:  8
Digite a nota da sua terceira prova:  10


Aprovado


In [35]:
idade = int(input("Por gentileza informe sua idade: "))

if idade < 18:
            print("Menor de idade ")
elif  idade >= 18 and idade <= 59:
            print("Adulto")

else: 
    print("Idoso")

Por gentileza informe sua idade:  17


Menor de idade 


In [39]:
usuario = "admin"
senha = "1234"

verificador_usuario = input("Digite o nome do usuario: ")
verificador_senha = input("Digite a senha do usuario: ")

if verificador_usuario == usuario and verificador_senha == senha:
    print("Login aprovado!")
else:
    print("Falha no login!")

Digite o nome do usuario:  admin
Digite a senha do usuario:  1234


Login aprovado!


In [45]:
compra =  float(input("Digte o valor da compra: "))
pagamento = float(input("Digte o valor que você pagou: "))
verificador = pagamento - compra

if verificador == 0:
    print("Pagamento aprovado")
elif verificador > 0:
    print(f"Seu troco é {verificador}")
else:
    print("Pagamento recusado, saldo insuficiente! ")

Digte o valor da compra:  10
Digte o valor que você pagou:  7


Pagamento recusado, saldo insuficiente! 


In [48]:
for numero in range(11):
    print(numero)

0
1
2
3
4
5
6
7
8
9
10


In [50]:
soma = 0
for numero in range(1, 101):
    print(numero) 
    soma = soma + numero
print(f"A soma de todos os números é: {soma}")

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
A soma de todos os números é: 5050


In [53]:
soma = 0
numero = -1
while numero != 0:
    numero = int(input("Digite um numero: "))
    print("Tente novamente.") 
    soma = numero + soma
print(f"A soma de todos os números até você acertar o numero escolhido é: {soma}")

Digite um numero:  2


Tente novamente.


Digite um numero:  1


Tente novamente.


Digite um numero:  4


Tente novamente.


Digite um numero:  7


Tente novamente.


Digite um numero:  2


Tente novamente.


Digite um numero:  0


Tente novamente.
A soma de todos os números até você acertar o numero escolhido é: 16


In [54]:
nome = input("Digite seu nome: ")
idade = int(input("Digite sua idade: "))
hab = int(input("Digite se possui CNH - [ 0 - NÃo ] 1 - SIM]: "))

if idade >= 18 and hab == 1:
    print(f"{nome} pode dirigir.")
else:
    print(f"{nome} não pode dirigir.")

Digite seu nome:  Pedro
Digite sua idade:  17
Digite se possui CNH - [ 0 - NÃo ] 1 - SIM]:  0


Pedro não pode dirigir.


In [56]:
numero = int(input("Digite um número"))
print(f"Tabuada de {numero}:")
for i in range(1, 11):
    print(f"{numero} x {i} = {numero * i}")

Digite um número 1


Tabuada de 1:
1 x 1 = 1
1 x 2 = 2
1 x 3 = 3
1 x 4 = 4
1 x 5 = 5
1 x 6 = 6
1 x 7 = 7
1 x 8 = 8
1 x 9 = 9
1 x 10 = 10


In [5]:
numeros = [7,8,10,4,5]
maior = max(numeros)
total = sum(numeros)
quantidade = len(numeros)
media = total / quantidade
menor = min(numeros)
print(f"O maior número é: {maior}")
print(f"A média dos números é: {media}")
print(f"O menor número é: {menor}")

O maior número é: 10
A média dos números é: 6.8
O menor número é: 4


In [10]:
numeros = [7,8,10,4,5]
for numero in numeros:
    if numero % 2 == 0:
        print(f"O número {numero} é par.")
    else:
        print(f"O número {numero} é ímpar.")
                 

O número 7 é ímpar.
O número 8 é par.
O número 10 é par.
O número 4 é par.
O número 5 é ímpar.


In [12]:
numeros = [7,8,10,4,5]
reverso = numeros[::-1]
print(f"A lista em ordem original é: {numeros}")
print(f"A lista em ordem reversa é: {reverso}")

A lista em ordem original é: [7, 8, 10, 4, 5]
A lista em ordem reversa é: [5, 4, 10, 8, 7]


In [14]:
for i in range (1,11):  #quando eu sei quantas vezes eu quero repetir.
    print(i)

opcao = 0
while opcao != "s":  #quando eu não sei quantas vezes eu quero repetir.
    opcao = input("Digite a opção que deseja [s - sair]")

1
2
3
4
5
6
7
8
9
10


Digite a opção que deseja [s - sair] s


In [27]:
numeros = []
quantos = int(input("Digite quantos números você deseja adicionar: "))
for i in range(quantos):
    deseja = int(input("Digite o número: "))
    numeros.append(deseja)
print(numeros)
def media(numeros):
    total = sum(numeros)
    media = total / len(numeros)
    return media
print(media(numeros))

Digite quantos números você deseja adicionar:  3
Digite o número:  10
Digite o número:  10
Digite o número:  10


[10, 10, 10]
10.0


In [43]:
def contar_vogais(texto):
    vogais = 'aeiou'
    contador = 0

    texto = texto.lower()
    for i in texto:
        if i in vogais:
            contador +=1
    return contador

texto_usuario = input('Digite uma frase: ')
resultado = contar_vogais(texto_usuario)
print(f'A sua frase: {texto_usuario}, tem {resultado} vogais')

Digite uma frase:  Pedro Alejandro Lima Dos Anjos


A sua frase: Pedro Alejandro Lima Dos Anjos, tem 11 vogais


In [44]:
peso = float(input("Digite o seu peso: "))
altura = float(input("Digite a sua altura: "))
def calculadora(imc):
    imc = peso / (altura*altura)
    return calculadora
print(f"Seu imc é: {imc:.2f}")


Digite o seu peso:  70
Digite a sua altura:  1.7


Seu imc é: 24.22


In [55]:
aluno = {
    "nome": "Ana",
    "nota": 8
}


In [58]:
nomes = ["Fernando", "Miguel", "André", "João"]

dicionario_carros = {"Volkswagen":["Gol","Jetta", "Golf","Touaregg","Taus"],
                    "Fiat":["Uno","Pálio","Bravo","Toro","Fastback"],
                    "Chevrolet":["Corsa","Tracker","S10","Onix"]}

print(dicionario_carros["Volkswagen"][2])
dicionario_carros.keys() #Chaves do dicionário
dicionario_carros.values() #Valores do dicionário

Golf


dict_values([['Gol', 'Jetta', 'Golf', 'Touaregg', 'Taus'], ['Uno', 'Pálio', 'Bravo', 'Toro', 'Fastback'], ['Corsa', 'Tracker', 'S10', 'Onix']])

In [56]:
produtos = {}

for _ in range(3):
    nome_produto = input("Digite o nome do produto: ")
    preco_produto = input("Digite o preço do produto: ")
    produtos[nome_produto] = preco_produto

print(produtos)

Digite o nome do produto:  bala
Digite o preço do produto:  1
Digite o nome do produto:  pipoca
Digite o preço do produto:  6
Digite o nome do produto:  bolacha
Digite o preço do produto:  4


{'bala': '1', 'pipoca': '6', 'bolacha': '4'}


In [2]:
import numpy as np

Array Numpy(Lista otimizada)

In [14]:
numeros = [2,4,8,16,32,64,128]

array_numeros = np.array(numeros)

print(array_numeros)

[  2   4   8  16  32  64 128]


operações vetorizadas

In [13]:
#numeros + 2 -> com uma lista normal dá erro
for numero in numeros: #com lista do python é necessario percorrer a lista
    print(numero * 2)
    
print(array_numeros * 2)

4
8
16
32
64
128
256
[  4   8  16  32  64 128 256]


In [17]:
# lista python: numeros / 2 -> não funciona
array_numeros + 2

array([  4,   6,  10,  18,  34,  66, 130])

In [19]:
array_aleatorios = np.array([22,17,13,14,15,12,17,21,23])

print(array_aleatorios % 2 == 0)

[ True False False  True False  True False False False]


<b> filtro condicional <b>

In [27]:
print(array_aleatorios % 2 == 0)

array_pares = array_aleatorios % 2 == 0
array_impares = array_aleatorios % 2 == 1

print(array_aleatorios[array_pares])
print(array_aleatorios[array_impares])

[ True False False  True False  True False False False]
[22 14 12]
[17 13 15 17 21 23]


In [28]:
print(array_aleatorios[0])
print(array_aleatorios[0:2])

22
[22 17]


In [29]:
print("maiores que 20: ",array_aleatorios[array_aleatorios > 20]) #mostra apenas os valores maiores que 20
print("pares:", array_aleatorios[array_aleatorios % 2== 0]) #mostra apenas os valores pares
print("impares:", array_aleatorios[array_aleatorios % 2== 1]) #mostra apenas os valores impares

maiores que 20:  [22 21 23]
pares: [22 14 12]
impares: [17 13 15 17 21 23]


# Operação com Arrays

In [30]:
print(array_aleatorios)
print("Soma:", np.sum(array_aleatorios))
print("Média:", np.mean(array_aleatorios))
print("Mínimo:", np.min(array_aleatorios))
print("Máximo:", np.max(array_aleatorios))

[22 17 13 14 15 12 17 21 23]
Soma: 154
Média: 17.11111111111111
Mínimo: 12
Máximo: 23


# Lista de exercícios

In [32]:
#Dado o array [1,2,3,4,5], realize operações vetorizadas: *2, +10 e elevado ao quadrado.
array_numeros = np.array([1,2,3,4,5])

print(array_numeros * 2)
print(array_numeros + 10)
print(array_numeros ** 2.)

[ 2  4  6  8 10]
[11 12 13 14 15]
[ 1.  4.  9. 16. 25.]


In [33]:
#Dado o array de notas [7.5, 8.0, 6.5, 9.0, 5.5], calcule média, máximo e mínimo.
array_numeros = np.array([7.5, 8.0, 6.5, 9.0, 5.5])
print("Média:", np.mean(array_numeros))
print("Máximo:", np.max(array_numeros))
print("Mínimo:", np.min(array_numeros))

Média: 7.3
Máximo: 9.0
Mínimo: 5.5


In [34]:
#Normalize o array [10,20,30,40,50] dividindo todos os valores pelo maior valor.
array_numeros = np.array([10,20,30,40,50])
maior_numero = np.max(array_numeros)
dividir = maior_numero / array_numeros
print(dividir)

[5.         2.5        1.66666667 1.25       1.        ]


In [38]:
#Dado o array de idades [15,18,22,17,30,16], filtre apenas maiores de idade.
array_idades = np.array([15,18,22,17,30,16])
print(array_idades >= 18)

[False  True  True False  True False]


In [59]:
#Filtre valores maiores que 10 e menores que 25 no array [5,10,15,20,25,30].
valores = np.array([5,10,15,20,25,30])
print(valores[ (valores > 10) & (valores < 25)])



[15 20]


In [53]:
#Conte quantos valores são maiores ou iguais a 6 no array [4,6,7,5,8,3,9].
array_valores = np.array([4,6,7,5,8,3,9])
total = (array_valores >= 6) 
print(total)

[False  True  True False  True False  True]


In [64]:
#Aumente em 500 os valores menores que 2000 no array [1000,2000,3000,1500].
array_valores = np.array([1000,2000,3000,1500])
array_valores[array_valores < 2000] += 500 

print(array_valores)

[1500 2000 3000 2000]


In [17]:
#Dado produtos e preços, aplique aumento de 10% nos preços.
array_valores = np.array([10, 20, 30, 40])
array_valores = array_valores * 1.1

print(array_valores)

[11. 22. 33. 44.]


In [21]:
#Você está analisando preços. Crie um array, filtre os valores maiores que 25 e calcule a média desses valores. [10, 20, 30, 40, 50]
filtro = np.array([10, 20, 30, 40, 50])

filtro = filtro[filtro > 25]

print(np.mean(filtro))

40.0


In [32]:
#Você possui duas informações: idades e salários. Crie dois arrays e calcule a média dos salários das pessoas com idade maior que 25.
#idades = [18, 25, 30, 22, 40]
#salarios = [2000, 3000, 4000, 2500, 5000]
array_idades = np.array([18, 25, 30, 22, 40])
array_salarios = np.array([2000, 3000, 4000, 2500, 5000])

filtro = array_idades[array_idades > 25]
filtro_salario = array_salarios[array_idades > 25]
print("Média salarial:", np.mean(filtro_salario))

Média salarial: 4500.0


In [4]:
#Você precisa identificar posições específicas. Crie um array e retorne os índices onde os valores são maiores ou iguais a 7.
#[5, 7, 8, 4, 9]
array_numeros = np.array([5, 7, 8, 4, 9])
np.where(array_numeros > 7)



(array([2, 4]),)

In [5]:
#Crie um array com valores de 1 até 10. Filtre apenas os números pares.
array_numeros = np.arange(1,11)

print("pares:", array_numeros[array_numeros % 2== 0])

pares: [ 2  4  6  8 10]


In [8]:
#Crie um array com 10 números aleatórios entre 0 e 100. Calcule a média do array e filtre apenas os valores maiores que essa média.
from random import randint
lista_aleatorios = [randint(1,100) for i in range(10)]


print(lista_aleatorios)

[42, 30, 85, 6, 21, 88, 99, 81, 46, 89]


In [10]:
array_aleatorios = np.array(lista_aleatorios)
media = np.mean(array_aleatorios)

filtro = array_aleatorios[array_aleatorios > media]
filtro

array([85, 88, 99, 81, 89])

In [54]:
#Crie um array com as notas abaixo. Calcule a média geral e conte quantos valores estão acima da média.[5, 7, 8, 6, 4, 9, 10]
array_valores = np.array([5, 7, 8, 6, 4, 9, 10])

media = np.mean(array_valores)

filtro = len(array_valores[array_valores > media])

print(f"A média dos valores é: {media}")
print(f"Os valores acima da média são: {filtro}")

A média dos valores é: 7.0
Os valores acima da média são: 3


In [17]:
array_funcionario =np.array([])
array_salario = np.array([])
array_idade = np.array([])

vezes = int(input("Digite quantos funcionarios você deseja adicionar: "))
for i in range(vezes):
    nome = input("Informe o nome do funcionario: ")
    array_funcionario = np.append(array_funcionario, nome)
    
    idade = int(input("Informe a idade do funcionario: "))
    array_idade = np.append(array_idade, idade)
    
    salario = float(input("Informe o salario do funcionario: "))
    array_salario = np.append(array_salario, salario)

media_idade = np.mean(array_idade)
minimo_idade = np.min(array_idade)
maximo_idade = np.max(array_idade)

media_salario = np.mean(array_salario)
minimo_salario = np.min(array_salario)
maximo_salario = np.max(array_salario)

total_funcionarios = len(array_funcionario)     

print(f"A lista de nome dos funcionarios é: {array_funcionario}")
print(f"A lista de salario dos funcionarios é: {array_salario}")
print(f"A lista de idade dos funcionarios é: {array_idade}")
print(f"Na sua empresa contém um total de: {total_funcionarios} funcionarios, com uma média salárial de: {media_salario:.2f}, e a idade media de: {media_idade:.2f}")


Digite quantos funcionarios você deseja adicionar:  3
Informe o nome do funcionario:  Pedro Alejandro Lima Dos Anjos
Informe a idade do funcionario:  17
Informe o salario do funcionario:  0
Informe o nome do funcionario:  Ester Beatriz Olimpio
Informe a idade do funcionario:  16
Informe o salario do funcionario:  1000
Informe o nome do funcionario:  Wender Almeida
Informe a idade do funcionario:  16
Informe o salario do funcionario:  0


A lista de nome dos funcionarios é: ['Pedro Alejandro Lima Dos Anjos' 'Ester Beatriz Olimpio' 'Wender Almeida']
A lista de salario dos funcionarios é: [   0. 1000.    0.]
A lista de idade dos funcionarios é: [17. 16. 16.]
Na sua empresa contém um total de: 3 funcionarios, com uma média salárial de: 333.33, e a idade media de: 16.33


In [8]:
import pandas as pd

funcionarios = pd.DataFrame({"nome":["Leonardo","Fernando","Gustavo"],"salarios":[5000,6000,2500]})
funcionarios[funcionarios["salarios"] >5000]


,nome,salarios
1,Fernando,6000
